## Circleci version
version: 2.0

## Machine specific variable
jobs:
  build:
    macos:
      xcode: 12.0.0

## Build crc
    steps:
    - checkout
    - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
    - run: rm ~/.ssh/id_rsa || true
    - run: for ip in $(dig @1.1.1.1 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
    - run:
        name: Build project
        command: ./build.sh
    - run:
        name: create tar ball of the app
        command: tar -C ./out/Build/Products/Release -czf crc-tray-macos.tar.gz ./CodeReady\ Containers.app
    - store_artifacts:
        path: ~/project/crc-tray-macos.tar.gz
        destination: crc-tray-macos.tar.gz


workflows:
    version: 2
    build:
      jobs:
        - build
